// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWwYQhpc34sNsuyUfls-b6VY0bcHfEo04',
    appId: '1:234105057000:web:2b14e3e1db434af9d4235d',
    messagingSenderId: '234105057000',
    projectId: 'todolist-cf43f',
    authDomain: 'todolist-cf43f.firebaseapp.com',
    storageBucket: 'todolist-cf43f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhTY7pCtWbMtMGVZ8pC6jDd46G_c1eQQs',
    appId: '1:234105057000:android:f9a825674bc66bfad4235d',
    messagingSenderId: '234105057000',
    projectId: 'todolist-cf43f',
    storageBucket: 'todolist-cf43f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACvPCg3iUr8aAyzBCcGgJ0T5wwO5PrW_s',
    appId: '1:234105057000:ios:e402e8f5efa3d73fd4235d',
    messagingSenderId: '234105057000',
    projectId: 'todolist-cf43f',
    storageBucket: 'todolist-cf43f.firebasestorage.app',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACvPCg3iUr8aAyzBCcGgJ0T5wwO5PrW_s',
    appId: '1:234105057000:ios:e402e8f5efa3d73fd4235d',
    messagingSenderId: '234105057000',
    projectId: 'todolist-cf43f',
    storageBucket: 'todolist-cf43f.firebasestorage.app',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWwYQhpc34sNsuyUfls-b6VY0bcHfEo04',
    appId: '1:234105057000:web:ca2bc49d15fe36a9d4235d',
    messagingSenderId: '234105057000',
    projectId: 'todolist-cf43f',
    authDomain: 'todolist-cf43f.firebaseapp.com',
    storageBucket: 'todolist-cf43f.firebasestorage.app',
  );

}